# Note: You MUST load these PID parameters for all joints that are using the
# PositionJointInterface, otherwise the arm + gripper will act like a giant
# parachute, counteracting gravity, and causing some of the wheels to lose
# contact with the ground, so the robot won't be able to properly navigate. See
# https://github.com/ros-simulation/gazebo_ros_pkgs/issues/612
gazebo_ros_control:
  pid_gains:
    # these gains are used by the gazebo_ros_control plugin    
    gripper_joint1:
      p: 1
      i: 0.05
      d: 0.0001
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
      

    gripper_joint2:
      p: 1
      i: 0.05
      d: 0.0001
      i_clamp: 0.2
      antiwindup: false
      publish_state: true


    gripper_joint3:
      p: 1
      i: 0.05
      d: 0.0001
      i_clamp: 0.2
      antiwindup: false
      publish_state: true


    gripper_joint4:
      p: 0.1
      i: 0.05
      d: 0.0001
      i_clamp: 0.2
      antiwindup: false
      publish_state: true



