# Position Controllers ---------------------------------------
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - gripper_joint1

    
    
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    gripper_joint1: {trajectory: 0.2, goal: 0.2}
    
  stop_trajectory_duration: 0.5
  state_publish_rate:  500
  action_monitor_rate: 10


