# Note: You MUST load these PID parameters for all joints that are using the
# PositionJointInterface, otherwise the arm + gripper will act like a giant
# parachute, counteracting gravity, and causing some of the wheels to lose
# contact with the ground, so the robot won't be able to properly navigate. See
# https://github.com/ros-simulation/gazebo_ros_pkgs/issues/612
gazebo_ros_control:
  pid_gains:
    # these gains are used by the gazebo_ros_control plugin    
    R_thumb_MCP_joint1:
      p: 0.05
      i: 0.03
      d: 0.0001
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
      

    R_thumb_MCP_joint2:
      p: 0.2
      i: 0.08
      d: 0.0002
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
      


    R_thumb_PIP_joint:
      p: 0.2
      i: 0.08
      d: 0.0002
      i_clamp: 0.2
      antiwindup: false
      publish_state: true


    R_thumb_DIP_joint:
      p: 0.2
      i: 0.08
      d: 0.0002
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
      
    R_index_MCP_joint:
      p: 1
      i: 0.05
      d: 0.0001
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    # the following gains are used by the gazebo_mimic_joint plugin
    R_index_DIP_joint:
      p: 1
      i: 0.05
      d: 0.0001
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
      
    R_middle_MCP_joint:
      p: 1
      i: 0.05
      d: 0.0001
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
      

    R_middle_DIP_joint:
      p: 1
      i: 0.05
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true



    R_ring_MCP_joint:
      p: 1
      i: 0.05
      d: 0.0001
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
      

    R_ring_DIP_joint:
      p: 1
      i: 0.05
      d: 0.0001
      i_clamp: 0.2
      antiwindup: false
      publish_state: true


    R_pinky_MCP_joint:
      p: 1
      i: 0.05
      d: 0.0001
      i_clamp: 0.2
      antiwindup: false
      publish_state: true


    R_pinky_DIP_joint:
      p: 0.5
      i: 0.05
      d: 0.0001
      i_clamp: 0.2
      antiwindup: false
      publish_state: true



