# Position Controllers ---------------------------------------
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1  
    - joint_11    
    - R_thumb_MCP_joint1
    - R_thumb_MCP_joint2
    - R_index_MCP_joint
    - R_middle_MCP_joint
    - R_ring_MCP_joint
    - R_pinky_MCP_joint
    
    
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    joint_1: {trajectory: 0.2, goal: 0.2} 
    joint_11: {trajectory: 0.2, goal: 0.2}       
    R_thumb_MCP_joint1: {trajectory: 0.2, goal: 0.2}
    R_thumb_MCP_joint2: {trajectory: 0.2, goal: 0.2}
    R_index_MCP_joint: {trajectory: 0.2, goal: 0.2}
    R_middle_MCP_joint: {trajectory: 0.2, goal: 0.2}
    R_ring_MCP_joint: {trajectory: 0.2, goal: 0.2}
    R_pinky_MCP_joint: {trajectory: 0.2, goal: 0.2}
    
  stop_trajectory_duration: 0.5
  state_publish_rate:  500
  action_monitor_rate: 10


